feat: remove caseworkers family name on `selfserve`
dvsa/olcs-common pull request #141
Opened 2024-07-23 11:50 UTC by gabrielg2020

## Description
remove caseworkers family name in messages on `selfserve`

## Before submitting (or marking as "ready for review")

- [x] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [x] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

2024-07-23 12:24 UTC, fibble approved these changes

2024-07-23 12:29 UTC, fibble reviewed
In refinement it was mentioned that the caseworkers name in full may end up on a snapshot available to self-serve users. Is that being dealt with separately?

2024-07-23 12:37 UTC, gabrielg2020 commented
@fibble 
> In refinement it was mentioned that the caseworkers name in full may end up on a snapshot available to self-serve users. Is that being dealt with separately?

I am not sure. I will message Kab to find out!

2024-07-23 12:59 UTC, JoshuaLicense requested changes

2024-07-23 12:59 UTC, JoshuaLicense commented on Common/src/Common/Service/Table/Formatter/AbstractConversationMessage.php
> +
The `__FILE__` magic constant relies on a file path that contains `selfserve` which is not going always the case. For example, the file path I have for this file is: `/var/www/html/vendor/olcs/olcs-common/Common/src/Common/Service/Table/Formatter/AbstractConversationMessage.php`.

Instead, I recommend taking advantage of the inheritance that's going on in this area. The frontend applications will each have a concrete class that extends this _abstract_ class. Each one of those concrete classes could have its own `getSenderName` that formats appropriately. 

A few unit tests for this logic would also be ideal!

Give me a shout if you need a hand.

2024-07-26 11:58 UTC, gabrielg2020 commented
Removing family name on snapshot is a PR on `backend`: https://github.com/dvsa/olcs-backend/pull/205

2024-07-29 12:18 UTC, JoshuaLicense approved these changes

2024-07-29 13:04 UTC, fibble approved these changes

2024-07-29 13:04 UTC, merged